# -*- coding: utf-8 -*-
"""bert_disinfo_clf_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXi0plLYwhgp7FTZldw2A9joh9ctw5K1
"""

import torch
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments, AutoTokenizer, AutoModelForSequenceClassification
from transformers import DataCollatorWithPadding
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import train_test_split

# Load pre-trained tokenizer and model
# Model names
# distilbert-base-german-cased
# deepset/gbert-large
# deepset/gbert-base
# LSX-UniWue/ModernGBERT_134M
model_name = "LSX-UniWue/ModernGBERT_134M"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

#!pip install transformers datasets torch scikit-learn pandas -q

# Load German Reviews dataset
df = pd.read_csv('/content/propaganda_binary.csv', sep=',', encoding='utf-8')
df.head()

df.info()

df['label'].hist()

#df['label'] = df['sentiment'].map({'negative': 0, 'positive': 1})

# Ensure labels are integers
df["label"] = df["label"].astype(int)

# Train-Test Split
# 1. 80% Train 20% Test Split
# 2. 50% Split am 20% Test Split -> 10% 10% Split

# 1.

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,  # 20% der Daten für den Rest
    random_state=42, # Für Reproduzierbarkeit
    stratify=df['label'] # Für gleichmäßige Verteilung der Zielvariable
)

print(f"Train-Set Zeilen (80%): {len(train_df)}")
print(f"Temp-Set Zeilen (20%): {len(temp_df)}")

# 2.

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5, # 50% des Temp-Sets geht an den Test-Set
    random_state=42,
    stratify=temp_df['label'] # Für gleichmäßige Verteilung der Zielvariable
)

print(f"Validierungs-Set Zeilen (10%): {len(val_df)}")
print(f"Test-Set Zeilen (10%): {len(test_df)}")

test_df.to_csv("test_propaganda_binary.csv")

# Visualisierung Train/Val/Test

train_df['label'].hist()
#test_df['label'].hist()
val_df['label'].hist()

# Get Text and Labels
train_texts = train_df["text"].tolist()
train_labels = train_df["label"].tolist()

val_texts = val_df["text"].tolist()
val_labels = val_df["label"].tolist()

test_texts = test_df["text"].tolist()
test_labels = test_df["label"].tolist()

# Convert to Hugging Face Dataset format
train_dataset = Dataset.from_dict({"text": train_texts, "label": train_labels})
val_dataset = Dataset.from_dict({"text": val_texts, "label": val_labels})
test_dataset = Dataset.from_dict({"text": test_texts, "label": test_labels})

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

# Tokenize train and test datasets
tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_val = val_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Set format for PyTorch
tokenized_train.set_format("torch", columns=["input_ids", "attention_mask", "label"])
tokenized_val.set_format("torch", columns=["input_ids", "attention_mask", "label"])

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none"
)

# Define evaluation metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    accuracy = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="macro")
    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    tokenizer=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    compute_metrics=compute_metrics,
)

# Train the model
trainer.train()

# Get predictions

prediction_results = trainer.predict(tokenized_test)

# Ausgabe der Ergebnisse
print("Vorhersage-Ergebnisse:")
print(prediction_results.metrics)

# Save metrics to json

import json

metrics = {
    "accuracy": prediction_results.metrics["test_accuracy"],
    "precision": prediction_results.metrics["test_precision"],
    "recall": prediction_results.metrics["test_recall"],
    "macro-f1": prediction_results.metrics['test_f1']
}

with open("modernbert_base_prediction_metrics.json", "w") as f:
    json.dump(metrics, f, indent=4)

# Get Classification Report

import numpy as np
import json

# Logits abrufen
logits = prediction_results.predictions

# Die vorhergesagte Klasse (Predicted Label) ist der Index des höchsten Logits
predicted_labels = np.argmax(logits, axis=-1)

# Die wahren Labels abrufen
true_labels = prediction_results.label_ids

print("\nEinige wahre Labels:", true_labels)
print("Einige vorhergesagte Labels:", predicted_labels)

# Save predictions

label_pred = {
    "predicted_labels": predicted_labels.tolist(),
    "true_labels": true_labels.tolist()
}

with open("gbert_prediction_labels.json", "w") as f:
    json.dump(label_pred, f, indent=4)

from sklearn.metrics import classification_report, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
# from google.colab import files

# labels
numerical_labels = [1, 0]
display_labels = ["Propaganda", "Non-Propaganda"]

cm = confusion_matrix(true_labels, predicted_labels, labels=numerical_labels)

# Anzeigen der Confusion Matrix
fig, ax = plt.subplots(figsize=(8, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=display_labels)


disp.plot(cmap=plt.cm.Blues, ax=ax)
ax.set_title("Confusion Matrix for Propaganda Detection")

file_name = "gbert_confusion_matrix_propaganda_detection.svg"
fig.savefig(file_name, format='svg', bbox_inches='tight')

# 5. Herunterladen der Datei in Google Colab
print(f"✅ Confusion Matrix als SVG gespeichert: {file_name}")
# Der Befehl files.download() löst den Download-Dialog in Ihrem Browser aus
files.download(file_name)

# --- 3.3 Fehleranalyse-DataFrame ---
# Isolieren der falsch klassifizierten Texte

import os
df_test_clean = test_df.reset_index(drop=True)
analysis_df = pd.DataFrame({
    'text': df_test_clean['text'].tolist(),
    'true_label': true_labels,
    'predicted_label': predicted_labels
})

misclassified_df = analysis_df[analysis_df['true_label'] != analysis_df['predicted_label']]

# Segmentierung in FP und FN
false_negatives = misclassified_df[
    (misclassified_df['true_label'] == 1) & (misclassified_df['predicted_label'] == 0)
]
false_positives = misclassified_df[
    (misclassified_df['true_label'] == 0) & (misclassified_df['predicted_label'] == 1)
]

# Konsolidierung und Speicherung aller Fehler
false_negatives['error_type'] = 'False Negative (Verpasste Propaganda)'
false_positives['error_type'] = 'False Positive (Falscher Alarm)'
all_errors_df = pd.concat([false_negatives, false_positives], ignore_index=True)

output_filename = "fehleranalyse_distilbert_propaganda.csv"
save_path_err = os.path.join(os.getcwd(), output_filename)
all_errors_df.to_csv(save_path_err, index=False, encoding='utf-8')

print(f"\n--- FEHLERANALYSE ---")
print(f"Gesamtanzahl Fehler: {len(misclassified_df)}")
print(f"False Negatives (Verpasste Propaganda): {len(false_negatives)}")

print("\nDetaillierter Klassifikationsbericht:")
print(classification_report(true_labels, predicted_labels))

