# -*- coding: utf-8 -*-
"""hugging_rag_clf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_IATEPNiZICbU95j46Sto7uNo-Wm8z9
"""

#!pip install haystack voyage-embedders-haystack -q

# Base libs
import pandas as pd
import os
import json
import uuid

# Document pipeline components
from haystack import Document, Pipeline
from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.document_stores.types import DuplicatePolicy
from haystack_integrations.components.embedders.voyage_embedders import VoyageDocumentEmbedder
from haystack.components.writers import DocumentWriter

# Chat and generator components
from haystack.dataclasses import ChatMessage
from haystack.components.builders import ChatPromptBuilder
from haystack.components.generators.chat import HuggingFaceLocalChatGenerator
from haystack.dataclasses import ChatMessage

# Embedding components
from haystack.components.retrievers.in_memory import InMemoryEmbeddingRetriever
from haystack_integrations.components.embedders.voyage_embedders import VoyageTextEmbedder

# Metrics
from datetime import datetime
from dotenv import load_dotenv
from sklearn.metrics import f1_score,  precision_score, recall_score, matthews_corrcoef

# import voyage key
from google.colab import userdata
from haystack.utils import Secret

os.environ["VOYAGE_API_KEY"] = userdata.get('VOYAGE_API_KEY')

# Get rid of unnecessary of warnings
import warnings

warnings.filterwarnings("ignore", message=".*Both `max_new_tokens` and `max_length` seem to have been set.*")

# switch models
german_models = {
    "SauerkrautLM:8b":"VAGOsolutions/Llama-3.1-SauerkrautLM-8b-Instruct",
    "SauerkrautLM:2b":"VAGOsolutions/SauerkrautLM-gemma-2-2b-it",
    "SauerkrautLM:1.5b":"VAGOsolutions/SauerkrautLM-1.5b" # Qwen 2:1.5b
}

meta_models = {
    "Llama 3.2:1b":"meta-llama/Llama-3.2-1B-Instruct",
    "Llama 3.2:3b":"meta-llama/Llama-3.2-3B-Instruct",
    "Llama 3.1:8b":"meta-llama/Llama-3.1-8B-Instruct"
}

google_models = {
    "Gemma 3:4b":"google/gemma-3-4b-it",
    "Gemma 3:1b":"google/gemma-3-1b-it",
    "Gemma 2:2b":"google/gemma-2-2b-it", # equivalent to SauerkrautLM-gemma-2-2b-it
}

microsoft_models = {
    "Phi-4:3.8b":"microsoft/Phi-4-mini-instruct"
}

qwen_models = {
    "Qwen 2.5:3b":"Qwen/Qwen2.5-3B-Instruct",
    "Qwen 2.5:1.5b":"Qwen/Qwen2.5-1.5B-Instruct",
    "Qwen 2:1.5b":"Qwen/Qwen2-1.5B-Instruct" # equivalent SauerkrautLM-1.5b
}

# Load data
df_train= pd.read_csv("/content/drive/MyDrive/Masterarbeit/propaganda_data/propaganda_train.csv", encoding="utf-8")
df_test = pd.read_csv("/content/drive/MyDrive/Masterarbeit/propaganda_data/propaganda_test.csv", encoding="utf-8")

# View data
df_test.head()

# Convert to Haystack Documents
documents = [
    Document(content=row["text"], meta={"label": row["label"]})
    for _, row in df_train.iterrows()
]

# Initialize Store and Index with Voyage 3 Large
doc_store = InMemoryDocumentStore(embedding_similarity_function="cosine")
retriever = InMemoryEmbeddingRetriever(document_store=doc_store, top_k=8)
doc_writer = DocumentWriter(document_store=doc_store)

doc_embedder = VoyageDocumentEmbedder(
    model="voyage-3-large",
    input_type="document"
)

text_embedder = VoyageTextEmbedder(model="voyage-3-large", input_type="query")

# Embed documents
docs_with_embeddings = doc_embedder.run(documents)
doc_store.write_documents(docs_with_embeddings["documents"], policy=DuplicatePolicy.OVERWRITE)

# Prompt
template = [
    ChatMessage.from_user(
        """
  Du bist ein erfahrener Kommunikationsforscher auf dem Gebiet der Propagandaforschung und sollst Sätze aus Social Media als Propaganda oder nicht klassifizieren.
  Sätze, welche Propaganda enthalten werden mit '1' klassifiziert, Sätze ohne Propaganda mit '0'.

  ## Beispiele
  {% for doc in documents %}
    Satz: {{ doc.content }}
    Klasse: {{ doc.meta['label'] }}
    --------------------
  {% endfor %}

  ## Vorgabe
  Gebe nur eines der beiden Klassen an. Deine Antwort lautet entweder '1' oder '0'.

  Satz: {{ query }}
  Antwort:
"""
    )
]

prompt_builder = ChatPromptBuilder(template=template, required_variables=["query", "documents"])

generator = HuggingFaceLocalChatGenerator(model=google_models["Gemma 2:2b"],
                                          task="text-generation",
                                          generation_kwargs={"max_new_tokens": 10, "temperature": 0.01, "max_length": None})
generator.warm_up()

# RAG Pipeline
pipeline = Pipeline()
# components
pipeline.add_component("text_embedder", text_embedder)
pipeline.add_component("retriever", retriever)
pipeline.add_component("prompt_builder", prompt_builder)
pipeline.add_component("llm", generator)

# Connect
pipeline.connect("text_embedder.embedding", "retriever.query_embedding")
pipeline.connect("retriever", "prompt_builder")
pipeline.connect("prompt_builder.prompt", "llm.messages")

def execute_pipeline(text: str) -> int:

    response = pipeline.run({"text_embedder": {"text": text}, "prompt_builder": {"query": text}})
    cls = response["llm"]["replies"][0].text

    # catches invalid input
    if "0" or "1" in cls:
        if "0" in cls:
            cls = 0
        elif "1" in cls:
            cls = 1
    return cls


def save_metrics_to_file(clf_name, provider, model_name, task, pred_metrics, folder_path: str) -> None:
        """
        save metrics to json file
        """
        #get pred_metrics
        try:
            if pred_metrics is None:
                raise ValueError("Predictions metrics not found.")



            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            unique_id = str(uuid.uuid4())[:8] # Short UUID for extra safety

            filename = f"{folder_path}\\metrics_{clf_name}_{task}_{unique_id}"

            meta_data = {
                "meta_data": {
                    "classifier_name": clf_name,
                    "provider": provider,
                    "model_name": model_name,
                    "task": task,
                    "timestamp": timestamp,
                    "run_id": unique_id
                }
            }

            complete_metrics = meta_data | pred_metrics

            with open(f"{filename}.json", "w") as f:
                json.dump(complete_metrics, f, indent=4)

        except Exception as e:
            raise Exception(f"An unexpected Error occurred while saving metrics: {str(e)}")

def rag_clf() -> None:
    # get labels
    actual_labels = df_test['label'].tolist()
    # empty list for classification
    predicted_labels = []

    # loop through test dataset
    for count, (_, row) in enumerate(df_test.iterrows()):
        cls = execute_pipeline(row['text'])
        print(f"No.: {count+1} | Prediction: {cls}")
        predicted_labels.append(cls)

    pred_metrics = {
        "predictions": predicted_labels,
        "Macro-F1": f1_score(actual_labels, predicted_labels, average='macro'),
        "Precision": precision_score(actual_labels, predicted_labels, average='macro'),
        "Recall": recall_score(actual_labels, predicted_labels, average='macro'),
        "MCC": matthews_corrcoef(actual_labels, predicted_labels)
    }

    print(f"Macro-F1: {pred_metrics["Macro-F1"]}")

    save_metrics_to_file("Gemma 2:2b", "google_genai", google_models["Gemma 2:2b"],"eight_shot_task", pred_metrics, folder_path="/content/drive/MyDrive/Masterarbeit/eval_data_test_pipeline/")

## Main
rag_clf()

# Test run LLM
# messages = [ChatMessage.from_user("Klassifiziere folgenden Satz als Negativ oder Positiv: Ich habe die Schnauze voll!!! ## Anweisung: Gebe **nur** an ob 'positiv' oder 'negativ'")]
# result = generator.run(messages)
# response_text = result['replies'][0]._content[0].text
# print(response_text)