# -*- coding: utf-8 -*-
"""log_reg_propaganda_clf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqB6DWSkeODbfQAeIybWbGOnubEo2Xk_
"""

# Libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from wordcloud import WordCloud

#  Load data
df = pd.read_csv("/content/propaganda_binary.csv", sep=',', index_col=0, encoding='utf-8')

df.info()

df['label'].hist()

# Ensure labels are integers
df["label"] = df["label"].astype(int)

# Train-Test Split
# 1. 80% Train 20% Test Split
# 2. 50% Split am 20% Test Split -> 10% 10% Split

# 1.

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,  # 20% der Daten für den Rest
    random_state=42, # Für Reproduzierbarkeit
    stratify=df['label'] # Für gleichmäßige Verteilung der Zielvariable
)

print(f"Train-Set Zeilen (80%): {len(train_df)}")
print(f"Temp-Set Zeilen (20%): {len(temp_df)}")

# 2.

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5, # 50% des Temp-Sets geht an den Test-Set
    random_state=42,
    stratify=temp_df['label'] # Für gleichmäßige Verteilung der Zielvariable
)

print(f"Validierungs-Set Zeilen (10%): {len(val_df)}")
print(f"Test-Set Zeilen (10%): {len(test_df)}")

# Feature Engineering

featurizer = TfidfVectorizer(decode_error='ignore')
X_train = featurizer.fit_transform(train_df['text'])
X_val = featurizer.transform(val_df['text'])

# Convert target variables to array

Ytrain = train_df['label'].to_numpy()
Yval = val_df['label'].to_numpy()

# Creating the model
model = LogisticRegression()
model.fit(X_train, Ytrain)
print("Train Accuracy:", model.score(X_train, Ytrain))
print("Validation Accuracy:", model.score(X_val, Yval))

# Transform test data
X_test = featurizer.transform(test_df['text'])

# Use transformed test data for prediction
Ptest = model.predict(X_test)
y_test = test_df['label'].to_numpy()

print("Test F1:", f1_score(y_test, Ptest, average='macro'))
print("Test Precision:", precision_score(y_test, Ptest, average='macro'))
print("Test Recall:", recall_score(y_test, Ptest, average='macro'))

# AUC
Prob_train = model.predict_proba(X_train)[:,1]
Prob_test = model.predict_proba(X_test)[:,1]
print("train AUC", roc_auc_score(Ytrain, Prob_train))
print("test AUC", roc_auc_score(Ytest, Prob_test))

cm = confusion_matrix(Ytrain, Ptrain)
cm

# Plotting the confusion matrix
def plot_cm(cm):
  classes = ['Propaganda', 'Non-Propaganda']
  df_cm = pd.DataFrame(cm, index=classes, columns=classes)
  ax = sns.heatmap(df_cm, annot=True, fmt='g')
  ax.set_xlabel("Predicted")
  ax.set_ylabel("Target")

plot_cm(cm)

# Get german stop words
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")  # Download stopwords if not already installed
german_stopwords = set(stopwords.words("german"))

print(german_stopwords)  # Output: {'aber', 'alle', 'allem', 'allen', ...}

propaganda = df[df['label'] == 1]
non_propaganda = df[df['label'] == 0]

# Combine all text into a single string
propaganda = " ".join(propaganda['text'])

# Generate WordCloud
wordcloud = WordCloud(width=800, height=400, background_color="white", stopwords=german_stopwords).generate(propaganda)

# Display the WordCloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

# Combine all text into a single string
non_propaganda = " ".join(non_propaganda['text'])

# Generate WordCloud
wordcloud = WordCloud(width=800, height=400, background_color="white", stopwords=german_stopwords).generate(non_propaganda)

# Display the WordCloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()