# -*- coding: utf-8 -*-
"""logreg_clf_with_bert_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BKxXTBsmh34zg8guRH6zyxFVNgWyzu8
"""

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('T-Systems-onsite/cross-en-de-roberta-sentence-transformer')

# Load data
import pandas as pd

test_data = pd.read_csv("/content/drive/MyDrive/Masterarbeit/propaganda_data/propaganda_test.csv", encoding="utf-8")
train_data = pd.read_csv("/content/drive/MyDrive/Masterarbeit/propaganda_data/propaganda_train.csv", encoding="utf-8")

# convert to embeddings
test_embeddings = model.encode(test_data["text"])
train_embeddings = model.encode(train_data["text"])

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Train log reg
clf = LogisticRegression(random_state=0)
clf.fit(train_embeddings, train_data['label'])

# Predict
y_pred = clf.predict(test_embeddings)

# Evaluate
print(classification_report(test_data['label'], y_pred))